name: Validate consul-template

on:
  workflow_dispatch:
  push:

jobs:
  validate-consul-template:
    runs-on: [self-hosted]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: run consul-template validation
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: myroot
        run: |
          echo "we run consul-template validation here!"

    services:
      consul:
        image: public.ecr.aws/hashicorp/consul:1.11.2
        ports:
          - 8500:8500
      vault:
        image: public.ecr.aws/hashicorp/vault:1.9.3
        options: --name vault
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: myroot
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: myroot
